-- user_skins 테이블 생성 마이그레이션 SQL
-- 사용자가 보유한 말풍선 스킨 목록을 영구 저장하는 테이블입니다.

CREATE TABLE IF NOT EXISTS public.user_skins (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    skin_id text NOT NULL,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT user_skins_pkey PRIMARY KEY (id),
    CONSTRAINT user_skins_user_id_skin_id_key UNIQUE (user_id, skin_id)
);

-- RLS (Row Level Security) 설정
ALTER TABLE public.user_skins ENABLE ROW LEVEL SECURITY;

-- 1. 사용자는 본인이 소유한 스킨 내역만 SELECT(조회)할 수 있도록 허용
CREATE POLICY "Users can view their own skins" 
ON public.user_skins 
FOR SELECT 
USING (auth.uid() = user_id);

-- 2. 결제 검증 Edge Function(service_role 권한) 또는 승인된 계정만 INSERT할 수 있도록 RLS 권한 부여
CREATE POLICY "Only authorized insert via Edge Functions" 
ON public.user_skins 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 인덱스 생성으로 성능 및 매핑 검색 최적화
CREATE INDEX IF NOT EXISTS user_skins_user_id_idx ON public.user_skins (user_id);
